### ISSUE TITLE
last row is partially not visible because of horizontal scrollbar

### ISSUE THREAD

**Issue by vorlov** [henrybuilt/react-sticky-table#9] opened 2017-05-18 16:01 UTC
you can check that on the first example

**Comment by maxhudson** [comment] 2017-05-18 22:31
@vorlov I'll see what I can do. I thought I had fixed this, but I guess not. Guessing you're on a Windows, not macOS?

**Comment by vorlov** [comment] 2017-05-20 21:32
Mac

**Comment by maxhudson** [comment] 2017-09-25 19:29
@vorlov Should be fixed now

**Comment by oldo** [comment] 2018-03-26 08:28
@maxhudson this appears to be an issue again:

<img width="717" alt="screen shot 2018-03-26 at 19 27 28" src="https://user-images.githubusercontent.com/4557648/37895024-d29d0dbe-312b-11e8-8413-5fdab76340bd.png">

**Comment by maxhudson** [comment] 2018-03-26 14:30
@oldo shoot - my bad. Scrollbars are the bane of my existence. Will work on a fix tonight or tomorrow. Should be reasonably easy to fix. You might be able to fix yourself with CSS in meantime, but not 100% sure how.

**Comment by oldo** [comment] 2018-03-26 22:40
Thanks @maxhudson

**Comment by maxhudson** [comment] 2018-03-29 22:12
@oldo v2.0.1 fixed the problem for me - hopefully it does for you too. If you wouldn't mind checking it out on Safari on your Mac (looks like mac scrollbar from the photo), I would greatly appreciate it. Safari was having trouble rendering the scrollbar for me.

**Comment by oldo** [comment] 2018-03-29 23:01
Hi @maxhudson 

As I mentioned in https://github.com/henrybuilt/react-sticky-table/issues/22 I am not using the component any more but I'm happy to test out in different browsers if you have some examples.

Have you updated the example at https://henrybuilt.github.io/react-sticky-table/ to use the latest version? They all appear the same to me as in the screenshot I originally posted in Chrome and in Safari I can't see any scrollbar at all.

**Comment by maxhudson** [comment] 2018-03-30 14:31
@oldo no - forgot to - thanks. Would you take a look at it now and see how it looks in safari?

**Comment by oldo** [comment] 2018-03-31 03:41
The extra space is being added at the bottom which is great, but scrollbars are not visible:

![screen shot 2018-03-31 at 14 41 08](https://user-images.githubusercontent.com/4557648/38159324-a58144c0-34f1-11e8-815c-58a6c4954ba0.png)

**Comment by maxhudson** [comment] 2018-04-04 17:28
@oldo thanks - i'll need to fix that somehow.

**Comment by gairon** [comment] 2018-08-07 09:50
The problem is still present on the Demo:
![image](https://user-images.githubusercontent.com/81073/43768592-5fcbacea-9a40-11e8-80cc-d4cabcc75bd7.png)
The most right column is overlapped by the vertical scrollbar.

**Comment by maxhudson** [comment] 2019-05-26 00:16
resolved in v3.0.1

**Closed by maxhudson** 2019-05-26 00:16 UTC
Labels: bug, help wanted
